name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  cache: true

            - name: Install Dependencies
              run: flutter pub get

            - name: Run Static Analysis
              run: flutter analyze

            - name: Run Tests
              run: flutter test
